apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-iyp6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-iyp6
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-iyp6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-iyp6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-iyp6
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dujy-tenant/rhtap-demo-app/hacbs-test-project-iyp6@sha256:e2e807abe4e9fbd23bd551080af165419e1d50d33ac4c48bfd5191900fff373f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
