apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-iyp6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dujy-tenant/rhtap-demo-app/hacbs-test-project-iyp6@sha256:db52f4a01075f517c7a5647e426ece27bcef5ed282d47f187f756091d399e5e6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
